# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20180501_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.TextField(default=True),
        ),
    ]
